### ISSUE TITLE
🐛 Missing toleration in csi-hcloud DaemonSet

### ISSUE THREAD

**Issue by Privatecoder** [syself/charts#50]
/kind bug

**What steps did you take and what happened:**

When deploying hetzner csi-hcloud:0.3.1 the resulting DaemonSet pods does not have tolerations set correctly.

[Should be](https://github.com/hetznercloud/csi-driver/blob/main/deploy/kubernetes/hcloud-csi.yml):
```
tolerations:
- effect: NoExecute
  operator: Exists
- effect: NoSchedule
  operator: Exists
- key: CriticalAddonsOnly
  operator: Exists
```
Is:
```
tolerations:
- effect: NoExecute
  operator: Exists
- key: CriticalAddonsOnly
  operator: Exists
```

**What did you expect to happen:**

Missing toleration should be available
```
- effect: NoSchedule
  operator: Exists
```
